export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export const FULL_SCREEN = 'FULL_SCREEN';
export const FULL_SCREEN_EXIT = 'FULL_SCREEN_EXIT';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';

export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOADING = 'USER_LOADING';
export const GET_ERRORS = "GET_ERRORS";
export const GET_SUCCESS = "GET_SUCCESS";
export const GET_COACH_VIEW = "GET_COACH_VIEW";
export const GET_COACH_VIEW2 = "GET_COACH_VIEW2";
export const LOAD_ASSOC_BRANCHES = "LOAD_ASSOC_BRANCHES";

export const LOAD_BRANCHES = "LOAD_BRANCHES";
export const LOAD_BATCHES = "LOAD_BATCHES";
